#!/usr/bin/python
import platform
import os

from lazyscripts import distro
from lazyscripts import pkgmgr

dist = distro.Distribution()

if dist.name not in ('opensuse'):	exit(1)
o = pkgmgr.get_pkgmgr(dist.name)
if not o:	exit(1)

if 'i686' == platform.machine():
	pkgname = "w32codecs"
else:
	pkgname = "w64codecs"

os.system(o.make_cmd('install', pkgname))
